// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHlwXsRfL9No-1-AHfAxxzXemlzFTIdA',
    appId: '1:170362111809:web:42aa61046cda9a754e03c0',
    messagingSenderId: '170362111809',
    projectId: 'crypto-dreamer-1d54f',
    authDomain: 'crypto-dreamer-1d54f.firebaseapp.com',
    storageBucket: 'crypto-dreamer-1d54f.firebasestorage.app',
    measurementId: 'G-CH77LVVHQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmqAHNtheTRiBs4O3JNiAld1a3dAmXPo',
    appId: '1:170362111809:android:432534923ca3743f4e03c0',
    messagingSenderId: '170362111809',
    projectId: 'crypto-dreamer-1d54f',
    storageBucket: 'crypto-dreamer-1d54f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03AsZqLsS8RuoLHcZxIjUtwWlNcr-bMM',
    appId: '1:170362111809:ios:872227479a650eb64e03c0',
    messagingSenderId: '170362111809',
    projectId: 'crypto-dreamer-1d54f',
    storageBucket: 'crypto-dreamer-1d54f.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03AsZqLsS8RuoLHcZxIjUtwWlNcr-bMM',
    appId: '1:170362111809:ios:872227479a650eb64e03c0',
    messagingSenderId: '170362111809',
    projectId: 'crypto-dreamer-1d54f',
    storageBucket: 'crypto-dreamer-1d54f.firebasestorage.app',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHlwXsRfL9No-1-AHfAxxzXemlzFTIdA',
    appId: '1:170362111809:web:af5fed348cd3fe1f4e03c0',
    messagingSenderId: '170362111809',
    projectId: 'crypto-dreamer-1d54f',
    authDomain: 'crypto-dreamer-1d54f.firebaseapp.com',
    storageBucket: 'crypto-dreamer-1d54f.firebasestorage.app',
    measurementId: 'G-G94P197DZT',
  );
}
